<?php
define("BR", "<br>\n");
define("TTL", "GESVENTAS APP");

define("LANGS", [
    'es' => [
        "lang" => "ESPAÑOL",
        "welcome" => "BIENVENIDO/A",
        "login" => "LOGIN",
        "register" => "REGISTRARSE",
        "logout" => "SALIR",
        "index" => "INICIO",
        "cart" => "CARRITO",
        "nodata" => "Porfavor, introduce tu usario y contraseña",
        "fail" => "Error en el usuario o contraseña",
        "user" => "Usuario",
        "pass" => "Contraseña",
        "idiom" => "Idioma",
        "initMssg" => "Formulario de entrada",
        "menu" => "Menú",
        "section" => "Sección",
        "filtreMssg" => "Esta es una sección de filtros",
        "mssgLabelProdCod" => "Código del producto",
        "search" => "Buscar",
        "cod" => "Código",
        "nom_prod" => "Nombre",
        "pvp" => "Precio",
        "prov" => "Proveedor",
        "imagen" => "Imágen",
        "exts" => "Existencias",
        "retrieve" => "Consulta",
        "new" => "Nuevo",
        "delete" => "Borrar",
        "update" => "Actualizar",
        "filters" => "Filtros",
        "mssgProdName" => "Nombre del producto",
        "mssgProdPrice" => "Precio del producto",
        "mssgProdProv" => "Proveedor del producto",
        "mssgProdImg" => "Imágen del producto",
        "mssgProdExts" => "Existencias del producto",
        "newProd" => "Añadir nuevo producto",
        "btnNewProd" => "Añadir"
    ],
    'en' => [
        "lang" => "ENGLISH",
        "welcome" => "WELCOME",
        "login" => "LOGIN",
        "register" => "REGISTER",
        "logout" => "LOGOUT",
        "index" => "INDEX",
        "cart" => "CART",
        "nodata" => "Please, enter your user and password",
        "fail" => "Wrong user or password",
        "user" => "User",
        "pass" => "Password",
        "idiom" => "Languaje",
        "initMssg" => "Input form",
        "menu" => "Menu",
        "section" => "Section",
        "filtreMssg" => "This is a filter section",
        "btnConsul" => "CONSULT",
        "mssgLabelProdCod" => "Product code",
        "search" => "Search",
        "cod" => "Code",
        "nom_prod" => "Name",
        "pvp" => "Price",
        "prov" => "Vendor",
        "imagen" => "Picture",
        "exts" => "Stock",
        "retrieve" => "Query",
        "new" => "New",
        "delete" => "Delete",
        "update" => "Update",
        "filters" => "Filters",
        "mssgProdName" => "Nombre del producto",
        "mssgProdPrice" => "Precio del producto",
        "mssgProdProv" => "Proveedor del producto",
        "mssgProdImg" => "Imágen del producto",
        "mssgProdExts" => "Existencias del producto",
        "newProd" => "Add new product",
        "btnNewProd" => "Add"
    ],
    'fr' => [
        "lang" => "FRANÇAIS",
        "welcome" => "BIENVENU",
        "login" => "LOGIN",
        "register" => "SE REGISTER",
        "logout" => "EXIT",
        "index" => "COMMENCER",
        "cart" => "CART",
        "nodata" => "S\'il vous plaît, entrez votre nom d'utilisateur et votre mot de passe",
        "fail" => "Erreur d'utilisateur ou de mot de passe",
        "user" => "Utilisateur",
        "pass" => "Mot de passe",
        "idiom" => "Langage",
        "initMssg" => "Formulaire de saisie",
        "menu" => "Menu",
        "section" => "Section",
        "filtreMssg" => "Ceci est une section de filtre",
        "btnConsul" => "CONSULTER",
        "mssgLabelProdCod" => "Code produit",
        "search" => "Chercher",
        "cod" => "Code",
        "nom_prod" => "Nom",
        "pvp" => "Prix",
        "prov" => "Fournisseur",
        "imagen" => "Photo",
        "exts" => "Stocker",
        "retrieve" => "Mettre en doute",
        "new" => "Nouveau",
        "delete" => "Effacer",
        "update" => "Mettre à jour",
        "filters" => "Filtres",
        "mssgProdName" => "Nombre del producto",
        "mssgProdPrice" => "Precio del producto",
        "mssgProdProv" => "Proveedor del producto",
        "mssgProdImg" => "Imágen del producto",
        "mssgProdExts" => "Existencias del producto",
        "newProd" => "Ajouter un nouveau produit",
        "btnNewProd" => "Ajouter"
    ]
]);

define('OPS', [
    //"login" => "login.php",
    // "register" => "registro.php",
    "logout" => "login.php",
    "index" => "index.php",
    "cart" => "carrito.php"
]);

define('CRUD', [
    "usr" => ["retrieve"],
    "adm" => ["retrieve", "new", "delete", "update"]]);
