<?php

//Constante para realizar un salto de linea en el documento HTML de manera mas sencilla
define("BR", "\n<br>\n");

//Constante para definir el nombre de nuestra aplicación web
define("TTL", "GESVENTAS APP");

/*
Constante que contiene un array por cada idioma que queramos tener disponible en nuestra
aplicación web, cada idioma contiene un array con las mismas claves, solo se modifican los
valores en función del idioma correspondiente
*/
define("LANGS", [
    'es' => [
        "lang" => "ESPAÑOL",
        "welcome" => "BIENVENIDO/A",
        "login" => "LOGIN",
        "register" => "REGISTRARSE",
        "logout" => "SALIR",
        "index" => "INICIO",
        "cart" => "CARRITO",
        "nodata" => "Porfavor, introduce tu usario y contraseña",
        "fail" => "Error en el usuario o contraseña",
        "user" => "Usuario",
        "pass" => "Contraseña",
        "idiom" => "Idioma",
        "initMssg" => "Formulario de entrada",
        "menu" => "Menú",
        "section" => "Sección",
        "filtreMssg" => "Esta es una sección de filtros",
        "mssgLabelProdCod" => "Código del producto",
        "search" => "Buscar",
        "cod" => "Código",
        "nom_prod" => "Nombre",
        "pvp" => "Precio",
        "prov" => "Proveedor",
        "imagen" => "Imágen",
        "existencias" => "Existencias",
        "retrieve" => "Consulta",
        "new" => "Nuevo",
        "delete" => "Borrar",
        "update" => "Actualizar",
        "filters" => "Filtros",
        "newProd" => "Añadir nuevo producto",
        "noProd" => "No se han encontrado productos",
        "noFilter" => "Quitar filtros",
        "prods" => "Productos",
        "add" => "Añadir",
        "notAvailable" => "Producto no disponible",
        "shoppingCart" => "Carrito de la compra",
        "empty" => "Carrito vacio",
        "addCart" => "Añadir al carrito"
    ],
    'en' => [
        "lang" => "ENGLISH",
        "welcome" => "WELCOME",
        "login" => "LOGIN",
        "register" => "REGISTER",
        "logout" => "LOGOUT",
        "index" => "INDEX",
        "cart" => "CART",
        "nodata" => "Please, enter your user and password",
        "fail" => "Wrong user or password",
        "user" => "User",
        "pass" => "Password",
        "idiom" => "Languaje",
        "initMssg" => "Input form",
        "menu" => "Menu",
        "section" => "Section",
        "filtreMssg" => "This is a filter section",
        "btnConsul" => "CONSULT",
        "mssgLabelProdCod" => "Product code",
        "search" => "Search",
        "cod" => "Code",
        "nom_prod" => "Name",
        "pvp" => "Price",
        "prov" => "Vendor",
        "imagen" => "Picture",
        "existencias" => "Stock",
        "retrieve" => "Query",
        "new" => "New",
        "delete" => "Delete",
        "update" => "Update",
        "filters" => "Filters",
        "newProd" => "Add new product",
        "noProd" => "No products found",
        "noFilter" => "Remove filters",
        "prods" => "Products",
        "add" => "Add",
        "notAvailable" => "Product not avilable",
        "shoppingCart" => "Shopping cart",
        "empty" => "Empty cart",
        "addCart" => "Add to cart"
    ],
    'fr' => [
        "lang" => "FRANÇAIS",
        "welcome" => "BIENVENU",
        "login" => "LOGIN",
        "register" => "SE REGISTER",
        "logout" => "EXIT",
        "index" => "COMMENCER",
        "cart" => "CART",
        "nodata" => "S\'il vous plaît, entrez votre nom d'utilisateur et votre mot de passe",
        "fail" => "Erreur d'utilisateur ou de mot de passe",
        "user" => "Utilisateur",
        "pass" => "Mot de passe",
        "idiom" => "Langage",
        "initMssg" => "Formulaire de saisie",
        "menu" => "Menu",
        "section" => "Section",
        "filtreMssg" => "Ceci est une section de filtre",
        "btnConsul" => "CONSULTER",
        "mssgLabelProdCod" => "Code produit",
        "search" => "Chercher",
        "cod" => "Code",
        "nom_prod" => "Nom",
        "pvp" => "Prix",
        "prov" => "Fournisseur",
        "imagen" => "Photo",
        "existencias" => "Stocker",
        "retrieve" => "Mettre en doute",
        "new" => "Nouveau",
        "delete" => "Effacer",
        "update" => "Mettre à jour",
        "filters" => "Filtres",
        "newProd" => "Ajouter un nouveau produit",
        "noProd" => "Aucun produit trouvé",
        "noFilter" => "Supprimer les filtres",
        "prods" => "Produits",
        "add" => "Ajouter",
        "notAvailable" => "Produit non disponible",
        "shoppingCart" => "Panier",
        "empty" => "Panier vide",
        "addCart" => "Ajouter au panier"
    ],
    'dc' => [
        "lang" => "DEUTSCH",
        "welcome" => "WILLKOMMEN ZU",
        "login" => "ANMELDUNG",
        "register" => "EINCHECKEN",
        "logout" => "HINAUSGEHEN",
        "index" => "ANFANG",
        "cart" => "WAGEN",
        "nodata" => "Bitte gib deinen Benutzernamen und dein Passwort ein",
        "fail" => "Benutzer- oder Passwortfehler",
        "user" => "Benutzer",
        "pass" => "Passwort",
        "idiom" => "Idiom",
        "initMssg" => "Eingabeformular",
        "menu" => "Speisekarte",
        "section" => "Abschnitt",
        "filtreMssg" => "Dies ist ein Filterabschnitt",
        "mssgLabelProdCod" => "Produktcode",
        "search" => "Suche",
        "cod" => "Code",
        "nom_prod" => "Name",
        "pvp" => "Preis",
        "prov" => "Anbieter",
        "imagen" => "Bild",
        "existencias" => "Lager",
        "retrieve" => "Anfrage",
        "new" => "Neu",
        "delete" => "Löschen",
        "update" => "Aktualisieren",
        "filters" => "Filter",
        "newProd" => "Neues Produkt hinzufügen",
        "noProd" => "Keine Produkte gefunden",
        "noFilter" => "Filter entfernen",
        "prods" => "Produkte",
        "add" => "Hinzufügen",
        "notAvailable" => "Produkt nicht verfügbar",
        "shoppingCart" => "Einkaufswagen",
        "empty" => "leerer Warenkorb",
        "addCart" => "In den warenkorb legen"
    ]
]);

//Constante que contiene las direcciones de las paginas que forman nuestra aplicación web
define('OPS', [
    //"login" => "login.php",
    // "register" => "registro.php",
    "logout" => "login.php",
    "index" => "front.php",
    "cart" => "carrito.php"
]);

//Constante que contiene las opciones CRUD que podremos realizar en función de nuestro rol
define('CRUD', [
    "cli" => ["retrieve"],
    "adm" => ["retrieve", "new", "delete", "update"]
]);
